service: poc-transcribe

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  deploymentMethod: direct
  timeout: 30
  iamRoleStatements: 
    - Effect: "Allow"        
      Action:
        - transcribe:StartTranscriptionJob       
        - transcribe:GetTranscriptionJob
        - s3:GetObject      
        - s3:PutObject       
      Resource: 
        - "*"
functions:
  transcribe-sync:
      handler: main.handler
      events:
        - http:
            path: transcribe-sync
            method: post